name: Auto Merge Upstream
on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: {}

permissions:
  actions: write
  contents: write

defaults:
  run:
    shell: bash

jobs:
  clean:
    name: Clean Actions
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        uses: ./.github/workflows/clean.yml
        with:
          CLEAN_TOKEN: ${{ github.token }}

  sync:
    name: Sync All Other Forks
    if: ${{ github.repository != 'socksthewolf/workflows' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Actions
        uses: thiagokokada/merge-upstream@v1.0.2
        with:
          branch: main

# this needs a github PAT in order to work via the GH API.
  bad:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: Run GH Sync
        run: "gh api --method POST -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2026-03-10' /repos/$REPO/merge-upstream -f 'branch=main'"
        env:
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}

