# Updates all repositories with either the wrangler or cloudflare tag that you own
#
# This will not work on any repositories that are technically forks, even if forked with the intent to not push back to mainline.
# The only fix to this is to disconnect from the fork network
#
# It is recommended to have an environment named wrangler-update,
# but you can also just set it in the repository secrets

name: Auto Update Wrangler
on:
  push:
    branches: "main"
    # Run whenever the wrangler-updates package updates
    # This is so we can piggyback off dependabot PRs
    paths:
      - "wrangler-updates/package.json"
      - "wrangler-updates/.node-version"

  workflow_dispatch: {}

# Probably could consolidate the bash scripts, but w/e
defaults:
  run:
    shell: bash

concurrency:
  group: wrangler
  cancel-in-progress: false
  queue: single

# Necessary for clean_actions, all other cases have more scoped permissions
permissions:
  actions: write

jobs:
  clean-actions:
    uses: ./.github/workflows/clean_actions.yml

  get-repos:
    name: Prepare Wrangler Update
    runs-on: ubuntu-latest
    environment: wrangler-update
    permissions:
      contents: read
    outputs:
      repos: ${{ steps.get-repos.outputs.repos }}
      node_version: ${{ steps.read.outputs.value }}
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v7

      - name: Read Global Node Version
        id: read
        run: |
          echo "Reading global node version"
          node_version=$(cat "wrangler-updates/.node-version")
          echo "The current global node version is v$node_version"
          echo "value=$node_version" >> "$GITHUB_OUTPUT"

      - name: Query Repos
        id: get-repos
        uses: raven-actions/get-repos@c6353ce68aeca50cdbef29c5e76a627cd5503c4a
        with:
          owner: ${{ github.repository_owner }}
          # You should pass a token that is NOT the WRITE_PR secret
          github-token: ${{ secrets.READ_REPO_TOKEN }}
          topics: "wrangler,cloudflare"
          operator: "OR"

  sync-repos:
    name: Update Wrangler For (${{ matrix.repo.name }})
    runs-on: ubuntu-latest
    needs: get-repos
    # make sure repos exist
    if: ${{ needs.get-repos.outputs.repos != '[]' }}
    environment: wrangler-update

    # Actual Config Settings
    env:
      # The name of the cloudflare workers types package
      WORKERS_TYPES: "@cloudflare/workers-types"
      # The global node version
      GLOBAL_NODE_VERSION: ${{ needs.get-repos.outputs.node_version }}

      # If we should force all repositories to use a specific version of node
      #
      # NOTE: this will also write .node-version to whatever
      # the version of GLOBAL_NODE_VERSION is (pulled from this repo's .node-version is)
      #
      # This can be turned off per repo by adding a file named .node-lock
      FORCE_NODE_VERSION: "true"

      # If we should commit the changes immediately or open a pull request
      AUTO_COMMIT: "true"

      # The commit message. If a Pull Request is being opened, this is the title of the pull request.
      COMMIT_MESSAGE: "Update Wrangler"
      # If opening a pull request, who is the assignee of the PR?
      PR_ASSIGN_TO: ${{ github.actor }}

      # If commits should be signed. If true, the commits will show up as whatever's in your GPG key
      # Otherwise, it will be github-actions[bot]
      SIGN_COMMITS: "true"

      # These are unused if SIGN_COMMITS == 'true'
      DEFAULT_USERNAME: ${{ github.actor }}
      DEFAULT_EMAIL: ""

    # If signing is off or the only repos being used are public
    # then these permissions are used
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        repo: ${{ fromJson(needs.get-repos.outputs.repos) }}
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
        with:
          persist-credentials: true
          token: ${{ secrets.CREATE_PR_TOKEN || secrets.GITHUB_TOKEN }}
          repository: ${{ matrix.repo.full_name }}

      - name: |-
          ${{ format('Node: Find Directory') }}
        id: node_directory
        # Welcome to the hack zone, I hate it here
        #
        # This is based on the necessity of wrangler.toml's presence
        # Probably not the best option, but w/e
        run: |
          dir=$(dirname $(realpath $(find . -name 'wrangler.toml')))
          dir=${dir/$WORKSPACE}
          dir=${dir#/}
          echo "dir=${dir}" >> "$GITHUB_OUTPUT"
          sep=""
          if [[ "$dir" != "" ]]; then
            sep="/"
          fi
          echo "ver=${dir}${sep}.node-version" >> "$GITHUB_OUTPUT"
          echo "ver_lock=${dir}${sep}.node-lock" >> "$GITHUB_OUTPUT"
          echo "lock=${dir}${sep}package-lock.json" >> "$GITHUB_OUTPUT"
          echo "pack=${dir}${sep}package.json" >> "$GITHUB_OUTPUT"
        env:
          WORKSPACE: ${{ github.workspace }}

        # Check to see if the package has a "types" run script
        # or if it needs workers-types
      - name: Read packages.json
        id: package_read
        uses: socksthewolf/github-action-json@2496d3db8d63643161ca74efa6e835d6cd09d86c
        with:
          path: ${{ steps.node_directory.outputs.pack }}

      - name: Check packages.json
        id: pkg_check
        if: ${{ success() && (steps.package_read.outputs.scripts || steps.package_read.outputs.devDependencies )}}
        run: |
          echo "Check for other tasks to do..."
          # Check for npm run types
          check_script_types=$(echo "$SCRIPT_DATA" | jq -r .types)
          if [[ -n "$check_script_types" ]] && [[ "$check_script_types" != null ]]; then
            echo "Has npm run types"
            echo "has_types_command=true" >> "$GITHUB_OUTPUT"
          else
            echo "Does not have npm run types"
            echo "has_types_command=false" >> "$GITHUB_OUTPUT"
          fi

          # Check for CF workers type usage
          check_dev_depends=$(echo "$DEV_DEPENDS" | jq -r ."\"$WORKERS_TYPES\"")
          if [[ -n "$check_dev_depends" ]] && [[ "$check_dev_depends" != null ]]; then
            echo "Needs wrangler type updates"
            echo "has_cf_types=true" >> "$GITHUB_OUTPUT"
          else
            echo "Does not need wrangler type updates"
            echo "has_cf_types=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          SCRIPT_DATA: ${{ steps.package_read.outputs.scripts }}
          DEV_DEPENDS: ${{ steps.package_read.outputs.devDependencies }}

      - name: |-
          ${{ format('Node: Check{0}Version', case(env.FORCE_NODE_VERSION == 'true', ' & Update Any ', ' ')) }}
        id: node_version
        run: |
          echo "Checking Node Version..."
          # Add .node-version if it's missing for whatever reason
          # (like I forgot or something)
          #
          # NOTE: This will bypass any .node-lock files
          if [[ ! -f "$VERSION_FILE" ]]; then
            echo "Repo does not have a .node-version file, adding it to version $NODE_VERSION!"
            echo "$NODE_VERSION" > "$VERSION_FILE"
            echo "node_version=$NODE_VERSION" >> "$GITHUB_OUTPUT"
            echo "updated_node=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # Read Contents of .node-version
          current_version=$(cat "$VERSION_FILE")
          echo "Currently using $current_version"

          # Check to see if we have a .node-lock file
          # if we do, do not update the version below.
          if [[ -f "$VERSION_LOCK" ]]; then
            echo "Version lock file exists, locking to $current_version"
            echo "node_version=$current_version" >> "$GITHUB_OUTPUT"
            echo "updated_node=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if [[ "$current_version" != "$NODE_VERSION" ]] && [[ "$FORCE_NODE_VERSION" == "true" ]]; then
            echo "Current version is v$current_version, updating to v$NODE_VERSION"
            echo "$NODE_VERSION" > "$VERSION_FILE"
            echo "node_version=$NODE_VERSION" >> "$GITHUB_OUTPUT"
            echo "updated_node=true" >> "$GITHUB_OUTPUT"
          else
            echo "Node version is up to date"
            echo "node_version=$current_version" >> "$GITHUB_OUTPUT"
            echo "updated_node=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          VERSION_FILE: ${{ steps.node_directory.outputs.ver }}
          VERSION_LOCK: ${{ steps.node_directory.outputs.ver_lock }}
          NODE_VERSION: ${{ env.GLOBAL_NODE_VERSION }}

        # Easy to see from the matrix if any node versions were updated
      - name: |-
          ${{ case(steps.node_version.outputs.updated_node == 'true',
            format('Node: Updated to v{0}', steps.node_version.outputs.node_version),
            'Node: No Update Needed') }}
        if: ${{ steps.node_version.outputs.updated_node == 'true' }}
        run: echo "version status"

      - name: |-
          ${{ format('Node: Install v{0}', steps.node_version.outputs.node_version) }}
        id: node
        uses: actions/setup-node@v7
        with:
          cache: "npm"
          cache-dependency-path: ${{ steps.node_directory.outputs.lock }}
          node-version-file: ${{ steps.node_directory.outputs.ver }}
          package-manager-cache: true

      - name: |-
          Install Wrangler ${{ case(steps.pkg_check.outputs.has_types_command == 'true', '& Build Types', '') }}
        run: |
          echo "Running updates..."
          # Move to the correct working directory
          if [[ -n "$NODE_DIR" ]]; then
            echo "moved directory to $NODE_DIR"
            cd $NODE_DIR
          fi

          # Run all node commands

          # Install Wrangler
          echo "Installing wrangler latest..."
          npm install wrangler@latest --save-dev

          # Install Workers Types if needed
          if [[ "$NEEDS_CF_TYPES" == "true" ]]; then
            echo "Install latest CF types..."
            npm install $WORKERS_TYPES@latest --save-dev
          fi

          # Install all other packages and run types if necessary
          if [[ "$NEEDS_TYPES" == "true" ]]; then
            echo "Building types..."
            npm install && npm run types
          fi
        env:
          NODE_DIR: ${{ steps.node_directory.outputs.dir }}
          NEEDS_TYPES: ${{ steps.pkg_check.outputs.has_types_command == 'true' }}
          NEEDS_CF_TYPES: ${{ steps.pkg_check.outputs.has_cf_types == 'true' }}

        # Set up the GPG Key for Signing Commits
      - name: ${{ case(env.SIGN_COMMITS == 'true', 'Doing:', 'Skipping:') }} Setup GPG Key
        id: import-gpg
        if: ${{ env.SIGN_COMMITS == 'true' }}
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

        # This is a bit silly, but it's the best way to combine the output of the GPG step
        # or creating our own data based on run environment
      - name: Prepare Deploy Output
        id: precommit
        run: |
          echo "Preparing for deployment..."
          echo "author=$IN_AUTHOR" >> "$GITHUB_OUTPUT"
          echo "email=$IN_EMAIL" >> "$GITHUB_OUTPUT"
          echo "name=$IN_NAME" >> "$GITHUB_OUTPUT"
        env:
          IN_AUTHOR: |-
            ${{ case(env.SIGN_COMMITS == 'true',
              format('{0} <{1}>', steps.import-gpg.outputs.name, steps.import-gpg.outputs.email),
              format('{0} <{1}>', env.DEFAULT_USERNAME, env.DEFAULT_EMAIL)
            ) }}
          IN_NAME: ${{ case(env.SIGN_COMMITS == 'true', steps.import-gpg.outputs.name, env.DEFAULT_USERNAME) }}
          IN_EMAIL: ${{ case(env.SIGN_COMMITS == 'true', steps.import-gpg.outputs.email, env.DEFAULT_EMAIL) }}

      - name: ${{ case(env.AUTO_COMMIT == 'true', 'Doing:', 'Skipping:') }} Commit Files
        if: ${{ success() && env.AUTO_COMMIT == 'true' }}
        id: commit
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d
        with:
          commit_message: ${{ env.COMMIT_MESSAGE }}
          commit_author: ${{ steps.precommit.outputs.author }}
          commit_user_name: ${{ steps.precommit.outputs.name }}
          commit_user_email: ${{ steps.precommit.outputs.email }}
          # All Commits are Signed
          commit_options: ${{ case(env.SIGN_COMMITS == 'true', '-S', '') }}

      - name: |-
          ${{ case(env.AUTO_COMMIT == 'true',
          format('Commit Result: {0}', case(steps.commit.outputs.changes_detected == 'true', 'Committed', 'No Changes')),
          'Skipped: Uses PRs') }}
        if: ${{ success() && steps.commit.outcome == 'success' }}
        run: echo "Commit Result!"

      - name: ${{ case(env.AUTO_COMMIT == 'false', 'Doing:', 'Skipping:') }} Create Pull Request
        if: ${{ success() && env.AUTO_COMMIT == 'false' }}
        id: pull-request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          token: ${{ case(env.SIGN_COMMITS == 'true', secrets.CREATE_PR_TOKEN || secrets.GITHUB_TOKEN, secrets.GITHUB_TOKEN) }}
          delete-branch: true
          commit-message: ${{ env.COMMIT_MESSAGE }}
          sign-commits: ${{ case(env.SIGN_COMMITS == 'true', false, true) }}
          title: "Chore: Wrangler Update"
          assignees: ${{ env.PR_ASSIGN_TO }}
          committer: ${{ steps.precommit.outputs.author }}
          body: "All Wrangler + Safe Packages have been updated"
          branch: "chore/wrangler-update"

      - name: |-
          ${{ case(env.AUTO_COMMIT == 'false',
            format('PR Result: {0}', case(steps.pull-request.outputs.pull-request-number, 'Created', 'Not Necessary')),
            'Skipped: Uses Commits') }}
        if: ${{ success() && steps.pull-request.outcome == 'success' }}
        run: echo "PR Result!"
