# Cleans up Github Actions history
#
# Great for nuerodivergants!

name: Clean Actions
on:
  workflow_dispatch: {}
  workflow_call:

permissions:
  actions: write

defaults:
  run:
    shell: bash

concurrency:
  group: "clean_actions"
  cancel-in-progress: true

jobs:
  cleanup_actions:
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: igorjs/gh-actions-clean-workflow@5fa2e3a4fdd40e3e7098645a0b8df08624352e5e
        id: clean
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          runs_to_keep: 1
          runs_older_than: 0
      - name: Outputs
        if: success()
        run: |
          echo "Run Output:"
          echo "Total runs found: ${{ steps.clean.outputs.total-runs-found }}"
          echo "Runs deleted: ${{ steps.clean.outputs.runs-deleted }}"
          echo "Runs failed: ${{ steps.clean.outputs.runs-failed }}"
          echo "API requests: ${{ steps.clean.outputs.total-api-requests }}"
          echo "Rate limit hits: ${{ steps.clean.outputs.rate-limit-hits }}"