name: Clean Deploys
on:
  workflow_call:
    inputs:
      environment:
        description: "The Github environment name to clean up deploys for"
        type: string
        required: true

permissions:
  deployments: write

concurrency:
  group: "clean_deploys"
  cancel-in-progress: false
  queue: max

jobs:
  clean_deploys:
    name: Clean
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Delete
        uses: strumwolf/delete-deployment-environment@035f6d27c8b8951729f4d71b2d3d6a7975139476
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ inputs.environment }}
          onlyRemoveDeployments: true