name: ESLint
on:
  workflow_call:
    inputs:
      ref:
        description: "Pass github.ref"
        type: string
        required: true

permissions:
  contents: read
  security-events: write

jobs:
  eslint:
    name: Run ESLint scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.ref }}

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          cache: "npm"
          node-version-file: ".node-version"
          package-manager-cache: true

      - name: Install ESLint
        run: |
          npm install
          npm install @microsoft/eslint-formatter-sarif@3.1.0

      - name: Read packages.json
        id: package_read
        uses: socksthewolf/github-action-json@main
        with:
          path: "package.json"

      - name: Check & Run Build
        id: pkg_check
        run: |
          echo "Check for other tasks to do..."
          check_script_build=$(echo "$SCRIPT_DATA" | jq -r .build)
          if [[ -n "$check_script_build" ]] && [[ "$check_script_build" != null ]]; then
            echo "Has npm run build"
            npm run build
          else
            echo "Does not need build"
          fi
        env:
          SCRIPT_DATA: ${{ steps.package_read.outputs.scripts }}

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx eslint .
          --config eslint.config.ts
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true